[package]
name = "hartex_localization_core"
version = "0.14.0"
edition = "2024"
description = """
Localization infrastructure for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.87.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_localization_bindings = { path = "../hartex-localization-bindings" }
hartex_localization_loader = { path = "../../localization/hartex-localization-loader" }

fluent-bundle = "0.15.3"
fluent-syntax = "0.11.1"
intl-memoizer = "0.5.2"
lazy_static = "1.5.0"
miette = "7.5.0"
unic-langid = { version = "0.9.5", features = ["macros"] }

[features]
