[workspace]
members = [
    "hartex",
    "cmdsys",
    "conftoml",
    "base",
    "dbmani",
    "driver",
    "env",
    "eventsys",
    "localization/impl",
    "localization/locale",
    "model",
    "plugins",
    "utils"
]

[profile.release]
opt-level = "s"