[package]
name = "hartex_discord_worker"
version = "0.14.0"
edition = "2024"
description = """
The worker component of the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.87.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_models = { path = "../../api-backend/hartex-backend-models" }

hartex_database_queries = { path = "../../database/hartex-database-queries" }

hartex_discord_commands = { path = "../hartex-discord-commands" }
hartex_discord_commands_core = { path = "../hartex-discord-commands-core" }
hartex_discord_core = { path = "../hartex-discord-core", features = [
    "async-runtime",
    "async-signal",
    "discord-model",
    "environment",
] }

hartex_localization_core = { path = "../../localization/hartex-localization-core" }

hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }
hartex_kafka_utils = { path = "../../rust-utilities/hartex-kafka-utils" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

chrono = { version = "0.4.39", features = ["clock"], default-features = false }
futures-util = "0.3.31"
hyper = { version = "1.6.0", features = ["client", "http1"] }
hyper-util = { version = "0.1.10", features = ["tokio"] }
miette = { version = "7.5.0", features = ["fancy"] }
once_cell = "1.20.3"
rdkafka = { version = "0.37.0", default-features = false, features = [
    "cmake-build",
    "external-lz4",
    "tokio",
] }
serde = "1.0.218"
serde_json = "1.0.139"
serde_scan = "0.4.1"
sha2 = "0.11.0-pre.4"
strip-ansi-escapes = "0.2.1"
tokio-postgres = "0.7.13"
tracing = { version = "0.1.41", features = ["log-always"] }
time = "0.3.37"

[features]
