[package]
name = "hartex_discord_commands_manager"
version = "0.5.1"
edition = "2021"
description = """
The commands manager of the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_discord_core = { path = "../hartex-discord-core", features = ["async-net", "async-runtime", "discord-model", "environment"] }

hartex_log = { path = "../../rust-utilities/hartex-log" }

clap = "4.4.10"
hyper = { version = "1.0.1", features = ["client", "http2"] }
hyper-trust-dns = { version = "0.5.0", features = ["native-tls"] }
miette = { version = "5.10.0", features = ["fancy"] }
owo-colors = "3.5.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
walkdir = "2.4.0"

[features]
