[package]
name = "hartex_discord_core"
version = "0.5.1"
edition = "2021"
description = """
The core library of the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.76.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = { version = "0.15.7", optional = true }
num_enum = "0.7.1"
num_enum_derive = "0.7.1"
socket2 = { git = "https://github.com/rust-lang/socket2.git", branch = "v0.4.x" }
tokio = { version = "1.35.0", optional = true }
twilight-gateway = { git = "https://github.com/TeamHarTex/twilight.git", branch = "next", optional = true }
twilight-http = { git = "https://github.com/TeamHarTex/twilight.git", branch = "next", optional = true }
twilight-mention = { git = "https://github.com/TeamHarTex/twilight.git", branch = "next", optional = true }
twilight-model = { git = "https://github.com/TeamHarTex/twilight.git", branch = "next", optional = true }
twilight-util = { git = "https://github.com/TeamHarTex/twilight.git", branch = "next", optional = true }

[features]
async-net = ["dep:tokio", "tokio?/net"]
async-runtime = ["dep:tokio", "tokio?/macros", "tokio?/rt", "tokio?/rt-multi-thread"]
async-signal = ["tokio?/signal"]
discord-gateway = ["dep:twilight-gateway"]
discord-http = ["dep:twilight-http"]
discord-mention = ["dep:twilight-mention"]
discord-model = ["dep:twilight-model"]
discord-util = ["dep:twilight-util"]
discord-util-builder = ["twilight-util?/builder"]
discord-util-snowflake = ["twilight-util?/snowflake"]
environment = ["dep:dotenvy"]
