[workspace]
members = [
    "hartex-localization-bindings",
    "hartex-localization-core",
    "hartex-localization-loader",
]

resolver = "3"

[profile.release]
codegen-units = 1
debug = true
lto = "fat"
