[package]
name = "hartex_backend_routes_v1"
version = "0.1.0"
edition = "2021"
description = """
Backend routes (API v1)
"""
license = "AGPL-3.0-only"
rust-version = "1.72.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_models_v1 = { path = "../hartex-backend-models-v1" }
hartex_backend_ratelimiter = { path = "../hartex-backend-ratelimiter" }
hartex_backend_status_util = { path = "../hartex-backend-status-util" }

hartex_eyre = { path = "../../rust-utilities/hartex-eyre" }
hartex_log = { path = "../../rust-utilities/hartex-log" }

governor = { git = "https://github.com/antifuchs/governor.git" }
rocket = { git = "https://github.com/SergioBenitez/Rocket.git", branch = "master", features = ["json"] }
serde_json = "1.0.100"
sqlx = { version = "0.7.0", features = ["runtime-tokio-native-tls", "postgres"] }

[features]
