[package]
name = "hartex_discord_commands"
version = "0.14.0"
edition = "2024"
description = """
Commands for the bot.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.87.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_backend_models = { path = "../../api-backend/hartex-backend-models" }

hartex_database_queries = { path = "../../database/hartex-database-queries" }

hartex_discord_cdn = { path = "../hartex-discord-cdn" }
hartex_discord_core = { path = "../hartex-discord-core", features = [
    "async-net",
    "discord-http",
    "discord-mention",
    "discord-model",
    "discord-util",
    "discord-util-builder",
    "discord-util-snowflake",
] }
hartex_discord_commands_core = { path = "../hartex-discord-commands-core", features = [
    "derive",
] }
hartex_discord_entitycache_core = { path = "../hartex-discord-entitycache-core" }
hartex_discord_entitycache_repositories = { path = "../hartex-discord-entitycache-repositories" }

hartex_localization_core = { path = "../../localization/hartex-localization-core" }

hartex_log = { path = "../../rust-utilities/hartex-log" }
hartex_discord_utils = { path = "../../rust-utilities/hartex-discord-utils" }

async-trait = "0.1.87"
fluent-bundle = "0.15.3"
futures = "0.3.31"
http-body-util = "0.1.2"
hyper = { version = "1.6.0", features = ["client", "http2"] }
hyper-util = { version = "0.1.10", features = ["http2", "tokio"] }
lazy_static = "1.5.0"
miette = "7.5.0"
rand = "0.9.0"
regex = "1.11.1"
serde_json = "1.0.140"
tokio-postgres = "0.7.13"

[features]
