[package]
name = "rest"
version = "0.1.0"
edition = "2021"
description = """
The rest process for the bot.
"""
license = "AGPL-3.0-only"
rust-version = "1.64.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../base", features = ["cmdline", "logging", "panicking"] }
env = { path = "../env" }

dashmap = "5.4.0"
hyper = { version = "0.14.23", default-features = false, features = ["client", "http1", "http2", "tcp"] }
hyper-rustls = { version = "0.23.1", default-features = false, features = ["http1", "http2", "webpki-tokio"] }
hyper-trust-dns = { version = "0.5.0", default-features = false }
log = "0.4.17"
tide = "0.17.0-beta.1"
serde = { version = "1.0.148", features = ["derive", "std"], default-features = false }
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["macros", "rt", "rt-multi-thread", "sync", "time"] }
url = "2.3.1"

[[bin]]
name = "rest"
path = "bin/main.rs"

[lib]
name = "rest"
crate-type = ["rlib"]
path = "lib/lib.rs"
