[package]
name = "hartex_backend_models_v1"
version = "0.3.0"
edition = "2021"
description = """
Backend routes (API v1)
"""
license = "AGPL-3.0-or-later"
rust-version = "1.73.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "=1.0.183", features = ["derive"] }
sqlx = { version = "0.7.0", features = ["chrono", "postgres", "runtime-tokio-native-tls"] }

[features]
