[package]
name = "hartex_localization_bindings"
version = "0.14.0"
edition = "2024"
description = """
Localization bindings for HarTex.
"""
license = "AGPL-3.0-or-later"
rust-version = "1.87.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hartex_localization_loader = { path = "../hartex-localization-loader" }

fluent-bundle = "0.15.3"
fluent-syntax = "0.11.1"
intl-memoizer = "0.5.2"
miette = "7.5.0"
proc-macro2 = "1.0.94"
quote = "1.0.39"
syn = "2.0.99"
unic-langid = { version = "0.9.5", features = ["macros"] }

[lib]
name = "hartex_localization_bindings"
proc-macro = true

[features]
