name: Lints

on:
  pull_request:
    branches:
      - nightly

env:
  CARGO_TERM_COLOR: always

jobs:
  ClippyAll:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustc-dev
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run Clippy
        run: python ./x.py clippy

  CodeSpellAll:
    name: CodeSpell
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@master
