name: Tests

on:
  push:
    branches:
      - nightly
      - stable
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  Linux:
    name: Linux (Full Build)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Build
        run: cargo build --release
        env:
          CFG_IS_STABLE: "false"
          CFG_VERSION_STR: "dummy version str"

  macOS:
    name: macOS (Full Build)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Build
        run: cargo build --release
        env:
          CFG_IS_STABLE: "false"
          CFG_VERSION_STR: "dummy version str"

  Windows:
    name: Windows (Full Build)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Build
        run: cargo build --release
        env:
          CFG_IS_STABLE: "false"
          CFG_VERSION_STR: "dummy version str"

  LinuxTest:
    name: Linux (Test)
    needs:
      - Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Test
        run: cargo test
        env:
          CFG_IS_STABLE: "false"
          CFG_VERSION_STR: "dummy version str"

  macOSTest:
    name: macOS (Test)
    needs:
      - macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Test
        run: cargo test
        env:
          CFG_IS_STABLE: "false"
          CFG_VERSION_STR: "dummy version str"

  WindowsTest:
    name: Windows (Test)
    needs:
      - Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: default
      - name: Test
        run: cargo test
        env:
          CFG_IS_STABLE: "false"
          CFG_VERSION_STR: "dummy version str"