name: Tests

on:
  workflow_dispatch:
  merge_group:
    types:
      - checks_requested
  pull_request:
  push:
    branches:
      - nightly
      - stable

env:
  CARGO_TERM_COLOR: always

jobs:
  BuildAll:
    name: Build
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools, rustc-dev
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Print Rust Version
        run: rustc --version --verbose
      - name: Run Build
        run: python ./x.py build

  TestAll:
    name: Test
    needs:
      - BuildAll
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools, rustc-dev
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Print Rust Version
        run: rustc --version --verbose
      - name: Run Build
        run: python ./x.py build -- discord-frontend
      - name: Run Tests
        run: python ./x.py test -- --ui --build-dir=build
